# Generated by Django 3.1.1 on 2020-11-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookpet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HelloId', models.IntegerField()),
                ('Hello', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pet',
            name='img',
            field=models.ImageField(upload_to='static/cookpet/images/'),
        ),
    ]
