# Generated by Django 3.1.1 on 2020-11-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookpet', '0004_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='lasttime',
        ),
    ]
