# Generated by Django 3.1.1 on 2020-11-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookpet', '0005_remove_pet_lasttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='advid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
