# Generated by Django 3.1.1 on 2020-11-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookpet', '0006_pet_advid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('star', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userpet',
            name='point',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
