# Generated by Django 3.1.1 on 2020-12-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookpet', '0008_auto_20201207_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='planid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
