# Generated by Django 3.1.1 on 2020-12-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookpet', '0009_meal_planid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='name',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='UserPetId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='img',
            field=models.ImageField(default=0, upload_to='static/cookpet/images/'),
            preserve_default=False,
        ),
    ]
