# Generated by Django 3.1.1 on 2020-12-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookpet', '0011_auto_20201207_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
