# Generated by Django 3.1.1 on 2020-12-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookpet', '0012_auto_20201208_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
    ]
