# Generated by Django 3.1.1 on 2020-12-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookpet', '0014_auto_20201210_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpet',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
