# Generated by Django 3.1.1 on 2020-12-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookpet', '0015_auto_20201211_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpet',
            name='lasttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
