# Generated by Django 3.1.1 on 2020-12-04 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okada', '0002_auto_20201204_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
